spring.application.name=LibraCore


spring.datasource.url=jdbc:mysql://localhost:3306/libra-core
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret-key=tuagxbwd^&*jhmd@hbsda@hbb32&8/jds"huuds^hdkslan8923bhkjsah23
jwt.expiration=300000